[project]
name = "tempoctrl"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.13.3",
    "aiosignal==1.4.0",
    "appnope==0.1.4",
    "arviz>=1.2.0",
    "asttokens==3.0.1",
    "attrs==25.4.0",
    "comm==0.2.3",
    "debugpy==1.8.19",
    "decorator==5.2.1",
    "executing==2.2.1",
    "frozenlist==1.8.0",
    "fsspec==2026.1.0",
    "idna==3.11",
    "ipykernel==7.1.0",
    "ipython==9.9.0",
    "ipython-pygments-lexers==1.1.1",
    "jedi==0.19.2",
    "jupyter-client==8.8.0",
    "jupyter-core==5.9.1",
    "kloppy==3.18.0",
    "lxml==6.0.2",
    "matplotlib-inline==0.2.1",
    "multidict==6.7.1",
    "nest-asyncio==1.6.0",
    "numpy==2.4.1",
    "packaging==26.0",
    "pandas==3.0.0",
    "parso==0.8.5",
    "pexpect==4.9.0",
    "platformdirs==4.5.1",
    "polars==1.37.1",
    "polars-runtime-32==1.37.1",
    "prompt-toolkit==3.0.52",
    "propcache==0.4.1",
    "psutil==7.2.1",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.3",
    "pyarrow==23.0.0",
    "pygments==2.19.2",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "pyzmq==27.1.0",
    "seaborn>=0.13.2",
    "six==1.17.0",
    "sortedcontainers==2.4.0",
    "stack-data==0.6.3",
    "tornado==6.5.4",
    "traitlets==5.14.3",
    "wcwidth==0.5.0",
    "yarl==1.22.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"